import { Metadata } from "next";

export const metadata: Metadata = {
  title: "IT Regulations Compliance | Quantum Blue",
  description: "Details on Quantum Blue's compliance with global IT regulations and standards.",
};

export default function ITRegulationsPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-24 space-y-12">
      <div className="space-y-4">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-white font-mono">
          IT REGULATIONS COMPLIANCE.
        </h1>
        <p className="text-zinc-500 font-mono text-sm uppercase tracking-widest">
          Global Standards & Frameworks
        </p>
      </div>

      <div className="prose prose-invert prose-zinc max-w-none font-mono text-sm leading-relaxed">
        <h2>1. Global Cryptographic Standards</h2>
        <p>
          Quantum Blue strictly adheres to the final Post-Quantum Cryptography (PQC) standards published by the National Institute of Standards and Technology (NIST). We implement <span className="font-bold text-white">FIPS 203 (ML-KEM)</span> for key encapsulation and <span className="font-bold text-white">FIPS 204 (ML-DSA)</span> for digital signatures. We do not use deprecated Round-3 submissions (Kyber/Dilithium).
        </p>

        <h2>2. Legal Evidence & Timestamping</h2>
        <p>
          Our timestamping authority operates in strict compliance with <span className="font-bold text-white">IETF RFC 3161</span>. Certificates and verification logs generated by the platform are formatted specifically to meet the evidentiary requirements of the <span className="font-bold text-white">Indian Evidence Act, 1872 — Section 65B(4)</span>, ensuring electronic records are legally admissible in courts.
        </p>

        <h2>3. Data Protection & Privacy Laws</h2>
        <p>
          Quantum Blue is designed with Privacy by Design principles to comply with:
          <ul>
            <li><span className="font-bold text-white">GDPR (General Data Protection Regulation):</span> Providing transparent data processing and ensuring data subject rights.</li>
            <li><span className="font-bold text-white">DPDPA (Digital Personal Data Protection Act, India):</span> Lawful processing of digital personal data within the territorial scope of India.</li>
            <li><span className="font-bold text-white">CCPA (California Consumer Privacy Act):</span> Safeguarding consumer privacy rights and data transparency.</li>
            <li><span className="font-bold text-white">UAE PDPL (Federal Decree-Law No. 45 of 2021):</span> Ensuring compliance with personal data protection laws within the UAE.</li>
          </ul>
        </p>

        <h2>4. DIFC / UAE</h2>
        <p>
          Quantum Blue's output format has been mapped to DIFC Electronic Transactions Law (DIFC Law No. 2 of 2017) and DIFC Courts (RDC Parts 28 & 29) requirements, alongside the UAE National Encryption Policy (NEP 2025). [Status: complete — legal review pending].
        </p>

        <h2>5. Audit Trails & CBOM</h2>
        <p>
          The platform generates Cryptographic Bill of Materials (CBOM) conforming to the <span className="font-bold text-white">CycloneDX</span> standard. This ensures organizations can maintain comprehensive, standardized audit trails of their cryptographic assets for regulatory compliance and zero-trust architectures.
        </p>
      </div>
    </div>
  );
}
