import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | Quantum Blue",
  description: "Privacy Policy and data handling practices for the Quantum Blue platform.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-24 space-y-12">
      <div className="space-y-4">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-white font-mono">
          PRIVACY POLICY.
        </h1>
        <p className="text-zinc-500 font-mono text-sm uppercase tracking-widest">
          Last Updated: September 2026
        </p>
      </div>

      <div className="prose prose-invert prose-zinc max-w-none font-mono text-sm leading-relaxed">
        <h2>1. Overview</h2>
        <p>
          Quantum Blue (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;) operates the quantum-blue.in SaaS platform. We are committed to protecting your personal information and your right to privacy. This Privacy Policy adheres to global standards including the GDPR, CCPA, and India&apos;s Digital Personal Data Protection Act (DPDPA).
        </p>

        <h2>2. Information We Collect</h2>
        <p>
          <strong>Account Information:</strong> When you register, we collect your name, email address, and organizational details to provision your API keys and access.
          <br /><br />
          <strong>Cryptographic Metadata:</strong> We process cryptographic signatures, hashes, and public keys required for hybrid PQC (ML-DSA-65) validation and RFC 3161 timestamp generation. <strong>We never collect or store your private keys.</strong>
        </p>

        <h2>3. How We Use Your Data</h2>
        <p>
          The data we collect is used strictly to provide, maintain, and improve the Quantum Blue platform. Cryptographic metadata is utilized solely for generating verifiable Evidence Records under the Indian Evidence Act §65B(4) and generating CBOMs.
        </p>

        <h2>4. Data Retention and Security</h2>
        <p>
          We employ post-quantum secure encryption (ML-KEM-768) for all data in transit. We retain account information as long as your account is active. Audit logs and public cryptographic metadata are retained immutably as required for legal non-repudiation.
        </p>

        <h2>5. Your Rights</h2>
        <p>
          Depending on your jurisdiction, you have the right to access, rectify, or erase your personal data. Please contact us to exercise these rights. Note that immutable cryptographic audit trails generated by our service cannot be altered or deleted.
        </p>

        <h2>6. Contact Us</h2>
        <p>
          If you have questions or comments about this policy, you may email our Data Protection Officer at <strong>prince.philip@quantum-blue.in</strong>.
        </p>
      </div>
    </div>
  );
}
